vns:
  iterMax: 2
construction:
  strategy: random
  levelMax: 10
  penalty:
    timeWindows: 100
    pickupDelivery: 10
    capacity: 1
optimization:
  strategy: cons2opt
  objective: span
  iterMax: 4
  levelMax: 50
