vns:
  iterMax: 2
construction:
  strategy: sortByTW
  levelMax: 30
  penalty:
    timeWindows: 100
    capacity: 1
    pickupDelivery: 1
optimization:
  strategy: cons2opt
  iterMax: 10
  levelMax: 10
