common:
  iterMax: 2
  maxTime: 100
construction:
  strategy: random
  levelMax: 10
  penalty:
    timeWindows: 100
    pickupDelivery: 10
    capacity: 1
optimization:
  objective: span
  gvns:
    iterMax: 4
    levelMax: 40
