common:
  iterMax: 4
  maxTime: 100
construction:
  strategy: random
  levelMax: 10
  penalty:
    timeWindows: 100
    pickupDelivery: 10
    capacity: 1
optimization:
  objective: span
  vns:
    iterMax: 2
    levelMax: 30
    localSearch: vnd
